server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hsp
    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#  jackson:
#    date-format: yy-MM-dd
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.houcheng.emplate: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

file:
  ip: localhost

shiro-redis:
  enabled: true
  redis-manager:
    host: 192.168.200.130:6379


markerhub:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization

#houcheng:
#  houcehng
#  expire: f4e2e52034348f86b67cde581c0f9eb5
#  secret: 604800
#  header: Authorization

